### ISSUE TITLE
Doorkeeper費用

### ISSUE THREAD

**Issue by sezemiadmin** [oss-gate/retrospective#1]
- kou さんが負担している状態なので、問題かなぁと思う

**Comment by ycatch** [comment]
こういうのがあります。
コワーキングスペース茅場町 Co-Edo: Doorkeeperを使用しているコミュニティの主催者をCo-Edoが支援します
http://blog.coworking.tokyo.jp/2016/08/doorkeeper.html

co-edoは、懇親会対応なんかもやってくれるそうです。
勉強会の参加者は、co-edoの利用料(1回1000円)が必要になります。

**Comment by kou** [comment]
Doorkeeperから移行するという案もあるけど、現時点で362人が登録しているので、それを捨てるのは忍びないという気持ちがある。（また人を集めるのはしんどそう。）

あと、どうせ移行するなら、OSS Gateな私たちはOSSなイベント管理ツールを使った方がいいんじゃないかという気持ちがある。もし、自分で動かすタイプのやつなら、運用が手間になって「OSS開発に継続して関わる人を継続して増やしたい」という私たちの目的を実現するネックになるかもしれないけど。。。なかったら自分たちで作る？みたいになるかもしれないけど。。。

**Comment by kou** [comment]
YassLabさんにスポンサーしてもらうことになりました！
https://oss-gate.github.io/sponsors/#yasslab

**Comment by kou** [comment]
現時点で551人登録しているので、[1月28日の時点](https://github.com/oss-gate/retrospective/issues/1#issuecomment-275829860)の1.5倍くらい（362人→551人）になっている！
