### ISSUE TITLE
ワークショップ終了後にDoorkeeperメッセージでミートアップの紹介をする

### ISSUE THREAD

**Issue by knokmki612** [oss-gate/retrospective#101]

**Comment by knokmki612** [comment]
gitterでミートアップのDoorkeeperイベントページのリンクを共有するのでも良いかも

**Comment by tdtds** [comment]
アナウンスのタイミングとしていいのは、アンケートがだいたい出揃って、先に提出しちゃった人たちが手持ち無沙汰になってる時間帯かも?

**Comment by knokmki612** [comment]
2018-09-08でアンケート回答が揃ってきたタイミングにミートアップのDoorkeeperイベントページのリンクを共有したら、ワークショップ参加者から参加申し込みがあった。効果がありそうなので続けたい
