### ISSUE TITLE
開催日までにやることリストがチェックボックス化されたタスクリスト、issueのテンプレートを用意しておき、準備がどこまで進んでいるかを可視化する

### ISSUE THREAD

**Issue by kou** [oss-gate/retrospective#106]

**Comment by knokmki612** [comment]
https://help.github.com/en/articles/about-automation-for-issues-and-pull-requests-with-query-parameters#supported-query-parameters

`https://github.com/oss-gate/workshop/issues/new?template=event_todo.md` みたいにすると、別のテンプレートが使えるんですね。なるほど

**Comment by knokmki612** [comment]
作って機能しているかなと思います
