### ISSUE TITLE
ワークショップのissueのステータスはワークショップそのもののステータスを示している（そのissueで扱っているフィードバックのステータスではない）ということで、ワークショップの終了時に閉じるものだという扱いにする（OSS Gateワークショップの様式）

### ISSUE THREAD

**Issue by piroor** [oss-gate/retrospective#111]

**Comment by knokmki612** [comment]
issueのbotを動かしていて思いましたが、開催予定イベントのリンクを置いても継続参加には結びついておらず(アンケート項目の「どこを見て参加しましたか？」でも特にbotを導入してから変化がない)、issueが閉じられること以外では積極的にbotを使い続けるメリットが薄いかなと思っています。

botを止めてワークショップのスライドにissueを閉じることを明示したほうが良いかなと思っています。

**Comment by knokmki612** [comment]
botが云々は抜きにして、そもそもがワークショップの作業メモのissueの寿命がフィードバックの内容が送り先のプロジェクトで何らかの形で反映か解決するまでなのか、ワークショップ終了時なのかがワークショップのシナリオなどで言語化されていないので、このissueが立てられたということですかね(このふりかえりにも参加していたはずだけど忘れてしまった)
