### ISSUE TITLE
会場提供者向けガイドを用意する

### ISSUE THREAD

**Issue by piroor** [oss-gate/retrospective#116]

**Comment by knokmki612** [comment]
ワークショップ開催準備のTODOチェックができるissueの雛形としてつくる

**Comment by knokmki612** [comment]
https://github.com/oss-gate/workshop/issues/1111 を参考につくれそう？

**Comment by knokmki612** [comment]
https://github.com/oss-gate/workshop/pull/1213 でworkshopリポジトリにテンプレートが追加され、東京の7月と9月のワークショップで使って試している
