### ISSUE TITLE
Discordを使ってオンラインでミートアップをやる

### ISSUE THREAD

**Issue by piroor** [oss-gate/retrospective#127]

**Comment by knokmki612** [comment]
とりあえずDiscordのサーバ(gitterにおけるルーム的なやつ)を作った https://gitter.im/oss-gate/general?at=5d120c6779a193262883684f

**Comment by tdtds** [comment]
Discordを使うってことは、voice chatの利用を考えていますか?

**Comment by knokmki612** [comment]
どんなやり方をとるか具体的には決めていませんが、ボイスチャット、ビデオチャット、画面共有を使えたら良いかなと思っています

**Comment by tdtds** [comment]
画面共有はいいですね。自分がもし参加するなら家族のいる自宅からなので、ボイスやビデオは使えないかなぁ。最小限の環境・装備でも参加できるといいですね。

**Comment by knokmki612** [comment]
できた！
