### ISSUE TITLE
24 Pull Requests みたいな、OSS活動の継続をモチベートするアプローチも何かやりようがあったりするのかも？

### ISSUE THREAD

**Issue by tricknotes** [oss-gate/retrospective#16]

**Comment by satoryu** [comment]
* [24 Pull Requests](https://24pullrequests.com/)

アドベントカレンダーのpull request 版なんですね。面白そう 😃

**Comment by sezemiadmin** [comment]
今年は間に合わないので、来年やってみたいですね、という話がありました
