### ISSUE TITLE
進行役とサポートメンターの決め方

### ISSUE THREAD

**Issue by knokmki612** [oss-gate/retrospective#17]
- 進行役はgitterなどで話し合って決めても問題なさそう
- サポートメンターはメンター申し込み時に「サポートメンターをやってみたいか」のアンケートを事前にしたほうがいいかも

**Comment by kou** [comment]
背景：サポートメンターを1回やってみたけど向いてない感があって、そういう気持ちになる人を減らしたい。

**Comment by kou** [comment]
初サポートメンターをサポートする仕組みがあるといいかも？たとえば、サポートメンター同士で相談してもいいよ！みたいな感じで。

**Comment by kou** [comment]
次回ワークショップで試してみよう！

なので、次回のワークショップは初サポートメンターを1人以上導入する。その人がいい感じにできるためのなにかを考えて、それを試す。たとえば進行役が初サポートメンターなのでフォローしようと周知するとか、30分に1回サポートメンター同士で相談するとか。

**Comment by kou** [comment]
やんなかったねー

進行役を増やすの方はやったねー
