### ISSUE TITLE
ビギナーの取り扱うOSSについて、メンターが門外漢だった場合に、、、、

### ISSUE THREAD

**Issue by hiroyuki-sato** [oss-gate/retrospective#19]
ビギナーの取り扱うOSSについて、メンターが門外漢だった場合に、「誰かメンター変わっていただけますか？」**気軽に**言える機会があるといいかも

対象OSSを決める際や、自己紹介の後に進行役の人が「ちょっとメンター難そうな人いますか」と聞くのはどうでしょう？

* 過去に、X Window Systemの修正をしたいビギナーの人がいた際に、「誰か変わって」と声が上がっていた。
* 自分は無理だと思ったら「誰か変わってください」というと思うが、メンター初めての人とか言い出しにくいのではないか？
* ミニ振り返りで、全然書いたことのないswiftのレビューをしたがちょっと辛かった。
* ミニ振り返りぐらいなら大丈夫だが、メンターとして担当するのは言語によっては辛い場合もある
* 会場には、自分よりふさわしいメンターもいるかも..

**Comment by knokmki612** [comment]
これはスライドにフィードバックされているので、閉じてよいと思いました！
