### ISSUE TITLE
Webサイトリニューアル

### ISSUE THREAD

**Issue by kou** [oss-gate/retrospective#29]
達成基準： https://oss-gate.github.io/ を自信を持って紹介できるURLにする。

これまで協力してくれた企業をスポンサーとしてサイトに載せる。（ありがたい！）

**Comment by ycatch** [comment]
とりあえず、少しデザインを変えてみました。

読みやすさのために、説明文もリライトしています。

https://github.com/oss-gate/oss-gate.github.io/commit/5a40927813c43247624f824d98f29cba3b5d6432

**Comment by tdtds** [comment]
カッコイイ！

こうなると、上のメニューバーにいきなり行動規範があるのは唐突感がありますね。DoorkeeperやGitterのようなイベント/コミュニケーションへのリンク集(?)に飛べるメニューに入れ替えたほうがいいかも。

**Comment by ycatch** [comment]
Topページの内容を、もう少し充実させてみたいと思います。
そこに、見出し＋簡単な説明＋各ページへのリンクを載せます。

今想定しているのは、

- 参加方法
- イベント情報
- コミュニケーションチャネル（Gitter、Twitter）
- ドキュメント（Github）
- レポート
- 協力企業

って感じです。
その上で、上のメニューバーを整理するといいかもしれないですね。

**Comment by ycatch** [comment]
上部メニューの文字を小さくして、ヘッダーっぽくしてみた。
ついでに(勝手ながら)、上部ヘッダーのワークショップレポートをフッターに移動。

これで、上部メニューの唐突さは、かなり抑えられたと思いますが、いかがでしょう。

**Comment by ycatch** [comment]
https://github.com/oss-gate/oss-gate.github.io/commit/66b846f27253527557b201fb3723a52a07d73ba8

**Comment by ycatch** [comment]
協力企業ページの追加
https://github.com/oss-gate/oss-gate.github.io/issues/22

**Comment by tdtds** [comment]
すでにDoorkeeperにログインしている状態で「DoorkeeperのOSS Gateコミュニティに参加する」のリンクをたどると、コミュニティのページに飛ばないですね(ユーザの状態によるかも知れないけど私は https://manage.doorkeeper.jp/ に飛んでしまいます)。これは https://oss-gate.doorkeeper.jp/ への直リンに変えた方がいいのかなぁ。

あと、やっぱり上部メニューに「行動規範」があるのは個人的に違和感あります。こういうものはフッタにあれば十分だと思うので。それより「開催予定」などがあったほうが嬉しい。

**Comment by knokmki612** [comment]
doorkeeperのリンクは修正しましたがいかがですか？

ヘッダ少しいじってみました
https://github.com/oss-gate/oss-gate.github.io/pull/23

**Comment by tdtds** [comment]
以下の2パターンはコミュニティのページに飛んだのでOKなようです。

* ログイン済み && コミュニティ参加済み
* ログイン未 && コミュニティ参加済み

コミュニティ未参加の状態はテストできてませんが……。

**Comment by kou** [comment]
> 達成基準： https://oss-gate.github.io/ を自信を持って紹介できるURLにする。

今のわれわれは自信を持って紹介できる！

**Comment by kou** [comment]
協力企業については別で扱おう！
