### ISSUE TITLE
Gateを通過したビギナーのその後をまとめてWebサイトに載せると宣伝効果がありそう。

### ISSUE THREAD

**Issue by kou** [oss-gate/retrospective#33]

**Comment by knokmki612** [comment]
1. 文章を集めるようのリポジトリを作る
2. 書いたものをプルリクエストしてもらう
3. <https://oss-gate.github.io/> に掲載する

という感じになるでしょうか。他には

* リポジトリのREADMEに文章をどう扱うか書く
* テキストのフォーマットを指定するかどうか
* 掲載する際は文章とアバター画像やワークショップ参加時に立てたIssueのリンクをつけるとか

みたいなことを考えました

**Comment by sezemiadmin** [comment]
書いてもらうときに簡単なテンプレを用意していると書きやすいかもと思いました

- なぜ参加したのか?
- どんなことをやったのか?
- これからどうしたいか?
- まとめ

**Comment by kou** [comment]
やんなかったねー
大変だもんね。
