### ISSUE TITLE
issue template の一番上に issue のタイトルのテンプレが入っていたほうがよさそう

### ISSUE THREAD

**Issue by mtsmfm** [oss-gate/retrospective#37]
スクロールした先にしかタイトルのテンプレが見えなかったので、最初から見えたほうがいいなぁと思いました。

**Comment by knokmki612** [comment]
とりあえず、何も考えずにタイトルのテンプレを上に持ってきたプルリクエストを用意しました。

見ていただければと思います

**Comment by mtsmfm** [comment]
遅くなってすみません、確認しました!
すごくよさそうです!
