### ISSUE TITLE
workshop/retrospective にREADMEが欲しい。

### ISSUE THREAD

**Issue by satoryu** [oss-gate/retrospective#38]
* 各会のディレクトリ下にあるファイルの使い方
* 回答時のファイル名のフォーマット
* aggregate.rb の使い方

あたりを書いたREADMEがあると、forkした先でも後からアンケートの記入の仕方が確認するのに役立ちそう。

**Comment by knokmki612** [comment]
READMEできましたね！
https://github.com/oss-gate/workshop/pull/549

**Comment by sezemiadmin** [comment]
* いつの間にか1つになった
* for 高専 では気付かなかった
* 順番を気にして、困惑することが無くなった
