### ISSUE TITLE
ワークショップ最初のスライドでサポータが何をして良く何をして悪いのか明確ではないように感じます

### ISSUE THREAD

**Issue by master-q** [oss-gate/retrospective#43]
ワークショップ最初のスライドでサポータが何をして良く何をして悪いのか明確ではないように感じます。

はじめてミートアップに参加しました。ところが須藤さんから以下の指摘を受けました:

* サポータはビギナーに直接答えを与えてはならない
* サポータは「xxxでWeb検索してみれば」というアドバイスもダメ
* なぜなら公式文書だけでOSS製品を扱えるようになるのが本来のOSSプロジェクトの姿だから
* qiitaなどに公式情報ではない間違った情報があふれているのは本来あるべき姿ではない思う

**Comment by kou** [comment]
○○はダメ、じゃなくて、○○という方針で、みたいな伝え方でそれぞれの人がいい感じに動けるようになる方がそれぞれの人の自由度があがっていいんじゃないかなぁと思っています。

これまで伝えてきたのは「一緒に考えて」「一緒に悩んで」「ビギナーにたくさん経験させて」みたいな感じです。

**Comment by master-q** [comment]
個人的にすぐ答にとびついてしまう脳味噌で生きてきてしまったので、「一緒に悩む」という方向で良いメンターになれるようになろうと感じました。

**Comment by knokmki612** [comment]
how-to-start-oss-development.rabに

> = サポーターへ
>   * 一緒に考えて
>  * 一緒に悩んで
>  * ビギナーにたくさん経験させて

みたいなスライドを1枚足すとよさそうですかね
