### ISSUE TITLE
東京ミートアップ2017-05-22を開発者枠だけでやってみる

### ISSUE THREAD

**Issue by knokmki612** [oss-gate/retrospective#44]
## もくもく会ではないとどうしたら言えるのか

* 会話がうながされること
* 元ビギナーとかが分からないことを周りの開発者に聞ける
* 開発者同士で興味があることを聞き合える
  * それぞれの守備範囲とか今日やってることがわかると、聞きやすい
  * Githubのissuesにイベント用のissueを立てて、コメントしてもらう
    * 守備範囲(普段なにを利用/開発しているか)
    *  今日何やるか

## 参加枠について

* 駆け出し開発者
* 開発者

でよさそう

## アイデア

* モブプログラミング
  * 分からない時に画面共有する(chromeキャストとかプロジェクター)
  * 作業の様子が見えると一緒に作業したくなるのでは？
* お菓子
  * 休憩とかもうやらないときに食べるお菓子のテーブルを用意する
  * 手隙になると他の開発者がやってることを見回るのでは？

**Comment by knokmki612** [comment]
http://koic.hatenablog.com/entry/oss-gate-tokyo-meetup-2017-04-13 より

> * 19:30から21:30の開催時間で、最初にチェックインを15分程度 (19:30-19:45) 、最後にチェックアウトを15程度 (21:15-21:30) 入れる

**Comment by knokmki612** [comment]
https://github.com/oss-gate/workshop/issues/377#issuecomment-291078105 より

> ### OSSを開発する人の内容
> 
> |時間|やること|
> |---|---|
> |19:15-19:30|開場|
> |19:30-19:40|アイスブレイク|
> |19:40-21:15|OSSの開発|
> |21:15-21:30|ミートアップのふりかえり|

**Comment by knokmki612** [comment]
https://github.com/oss-gate/workshop/issues/331#issuecomment-289287260 より

> 雑談場所みたいなスペースを用意しておいて（なにか飲食物があるといいのかしら。大阪ではスペースを用意していた。）、早くレポートを書き終わった人はそこに移動してざっくばらんに今日どうだった？とかもやっとしていることある？とかどうするといいかなぁ？とか話せるとふりかえりの時間でやっていたことと同じ効果を得られるかも。アンケートよりも柔軟に会話できるので、もしかしたら、もっと得られるかも。

https://github.com/oss-gate/workshop/issues/331#issuecomment-289369334 より

> ふりかえりをする気力の残ってない人には、レポートを書く気力も残ってないんじゃないかなぁw もっとも、終わった人が雑談できるスペース & 時間をとるのはいいと思う。ついでにピザとドリンクを買ってきてビアバッシュにしてしまってもいいかもしれない。

そう、私がいいたかったのはビアバッシュかもしれません(よく分かっていない)

**Comment by knokmki612** [comment]
今のところタイムテーブルはこうなりますかね

|時間|やること|
|---|---|
|19:15-19:30|開場|
|19:30-19:45|チェックイン|
|19:45-21:15|OSSの開発|
|21:15-21:30|チェックアウト|

開発に90分使えるのは良いですね！

**Comment by knokmki612** [comment]
> お菓子があると、いい休憩&コミュニケーションの場になって捗った https://github.com/oss-gate/retrospective/issues/11

こんなフィードバックがあったみたいです！

**Comment by koic** [comment]
Gitter の方で募集の下書きを書いたことをアナウンスしました。こちらの Issue からキャッチアップできる点がまだあると思います。気がついた点がありましたら添削頂けると助かります。

https://gitter.im/oss-gate/general?at=5912f03d0a783b6c0a82a7d8

**Comment by knokmki612** [comment]
@koic
[イベントページ](https://oss-gate.doorkeeper.jp/events/60514)作成ありがとうございます！

「開発者」と「駆け出し開発者」のイメージがつきやすい説明になっているかと思います。過去のイベントの説明文をベースに、適宜今回にあわせた内容になっていると思います。

**Comment by knokmki612** [comment]
開催までに、

* チェックインとチェックアウトの流れ(口頭とissueへのコメントの関係)
* お菓子(とお茶など)は本当に用意するのか

をどうするのかイメージを共有したいですね。というか、お菓子は私が言い出したので、私が用意できるなら用意しようかなあ

他に詰めておくべきことってありそうでしょうか。

**Comment by knokmki612** [comment]
> チェックインとチェックアウトの流れ(口頭とissueへのコメントの関係)

思ったのですが、口頭で話してもらってからissueにかいつまんで書いてもらえるよう誘導するのが良いかなと思いました。

チェックインでの今日やることや守備範囲、チェックアウトでのイベントや作業へのコメントにしても、先に喋ってもらったほうが書くことの整理がしやすいのかなと。

私の記憶では @koic さんは口頭だけで良いのではという考えだったと思うのですが、残すという観点でのissueへのコメントについて、どう思われますでしょうか？

**Comment by koic** [comment]
@knokmki612 検討事項の洗い出しありがとうございます。

> チェックインでの今日やることや守備範囲、チェックアウトでのイベントや作業へのコメントにしても、先に喋ってもらったほうが書くことの整理がしやすいのかなと。

はい。最初に口頭で話してもらうのが良いと思います。

> 私の記憶では @koic さんは口頭だけで良いのではという考えだったと思うのですが、残すという観点でのissueへのコメントについて、どう思われますでしょうか？

参加者の GitHub でのこれまでの活動やこれからの活動を知る意味で、「よろしくお願いします」くらいの書き込みでも「東京ミートアップ2017-05-22」共用の Issue にコメントするのは良いかなと思います (GitHub アカウントへの導線になる) 。どの程度書くかは参加者の裁量にお任せで良いと思っています。

> お菓子(とお茶など)は本当に用意するのか

例えば 10人くらいの参加者で座席で固まっての黙々にならないように、小休止の雑談場所としてお菓子置き場を用意するという流れでの話だったと思います。
いまの申込人数くらい (4名) であれば、ひとつのテーブル島で声が届く形で会話ができる規模なので、特に必要ないかなと思っています。

どうでしょうか？

**Comment by knokmki612** [comment]
@koic
> どの程度書くかは参加者の裁量にお任せで良いと思っています。

確かにコメントは参加者同士のGitHubアカウントの導線になるのが第一ですね。

> いまの申込人数くらい (4名) であれば、ひとつのテーブル島で声が届く形で会話ができる規模なので、特に必要ないかなと思っています。

確かにそうですね。今回はひとつのテーブルに集まって作業できそうなので、お菓子は必要なさそうです

**Comment by koic** [comment]
@knokmki612 はい。お願いします！また当日少し早めの時間なんかに相談できればなと思っています。

**Comment by knokmki612** [comment]
相談したい旨了解です！当日は19時前には会場につくかと思います。

**Comment by knokmki612** [comment]
今回のミートアップ用のissueの説明文を用意する必要がありました…！

**Comment by knokmki612** [comment]
チェックインの口頭での紹介は、5人で10分くらいで終わりました！

**Comment by knokmki612** [comment]
https://gitter.im/oss-gate/general?at=5922be150a783b6c0ac21ff0

> チェックイン
> * 名前
> * 普段やっていること
> * 今日何やる
> あたりのテンプレが良さそう

**Comment by knokmki612** [comment]
issueやgitterのurlを共有する工夫があると良さそう！

**Comment by knokmki612** [comment]
OSS Gateの雰囲気が知りたいという方が来てくれた！

**Comment by knokmki612** [comment]
会場のアクセスポイントの紹介を忘れていた！

**Comment by knokmki612** [comment]
さらっと独り言いいながら作業するスキル、ほしいですね

**Comment by koic** [comment]
東京ミートアップ2017-05-22の開催が終わったため Close します。 @knokmki612 5月の募集テキストを書く際に助かりました & フィードバックの記載ありがとうございました！

**Comment by koic** [comment]
来月 (6月) のミートアップも開発者枠だけでやってみる形式になります。

**Comment by sezemiadmin** [comment]
* ふりかえり
  * よかったこと
     * ワークショップのやり方から外れたので開催の工数が減った
     * やることが決まってない分、柔軟にサポートできた

**Comment by sezemiadmin** [comment]
* 他の地域でも開催できるようになるとよいなぁ
