### ISSUE TITLE
大阪のOSS Gateワークショップは安定運用に入ったっぽく見える。

### ISSUE THREAD

**Issue by sezemiadmin** [oss-gate/retrospective#61]
* どうやって上手く立ち上がったのかは知らない

**Comment by kou** [comment]
https://gitter.im/oss-gate/kansai で聞いてみるといいんじゃないかなぁと思いました！

**Comment by ogom** [comment]
## OSS Gate 関西の経緯

* 12月：大阪の居酒屋で打合せ
  * OSS Gate を関西で開催したいメンバーが話し合いをした。
* 2月：ファーストサーバ株式会社でOSS Gate大阪を開催
  * 須藤さんにモデーレータをしていただいて、基本の雰囲気を学んだ。
  * ここ参加された方は後に、後にサポーターで参加されるかたが多いです。
* 4月：クラスメソッド株式会社でOSS Gate大阪を開催
  * 関西のメンバーだけで開催できるかの素振りの気持ちでやった。
  * 参加者は知人に声をかけて、身内な感じで気軽でした。
  * 須藤さんの資料を参考に基本通りに進めた。
* 5月：大阪産業創造館でOSS Gate大阪を開催
  * 関西Ruby会議と合同で開催したら、参加者が多いと思ったら、少なかったです。
  * サポーターやビギナーが関西Ruby会議に参加していたもよう。
* 6月：アールスリーインスティテュートで打合せ
  * OSS Gate 関西のメンバーで話し合いをした。
* 7月：Hanare-IwakuraでOSS Gate京都を開催
  * OSS Gate 関西 のメンバーが共同で運営しているコワーキングでした。
* 8月：さくらインターネット株式会社でOSS Gate大阪を開催
  * サポーターはなんども参加されている方が多かった。
  * ビギナーは10人中で初参加が9人でした。
  * 新しくできたグランフロント大阪というビルの会場は人が集まりやすいかもしれません。

**Comment by tdtds** [comment]
ちなみにこの件は9/12のふりかえりで出たものなので、解決が必要なissueではないのでとりあえずクローズします。
「安定運用」というのは(東京からみていて)それなりの規模でだいたい定期的に開催できてるなという観測からみた感想みたいなものです。実態にあっているならすばらしいですね。

**Comment by kou** [comment]
東京以外の地域が東京の開催の知見を参考によりよい運用につなげられているように、
今後は、東京でも他の地域の知見を参考によりよい運用につなげる取り組みをできるといいんじゃないかなぁと思いました。
