### ISSUE TITLE
派生を含めたワークショップの開催頻度が上がっているのに対して、継続的に参加するサポーターがあまり増えていなかったらサポーター不足が深刻化しそう(実際はどうなのかな)

### ISSUE THREAD

**Issue by sezemiadmin** [oss-gate/retrospective#63]
* 企業で開催したワークショップで参加したサポーターに普通のワークショップに来てもらうよう、声を掛けてみよう
* 最後にワークショップを紹介してね、と言っていたが、それはビギナー向けになっていた
* それをサポーター向けにすると良さそう

**Comment by sezemiadmin** [comment]
* ワークショップのスライドの最後は、文脈的にはビギナーの人がサポーターになってね、という締め
* 今来ているサポーターにも次も来てね、という話を入れるのはどうだろう

**Comment by tdtds** [comment]
duplicated with #62 , close.
