### ISSUE TITLE
ミートアップ登録時のアンケート「取り組む予定のOSS」について、SNS告知に活用できるようになど変更したい

### ISSUE THREAD

**Issue by knokmki612** [oss-gate/retrospective#73]
現状の「取り組む予定のOSS」の質問文は、個人的には

* 何を書いてほしいか分かりやすい
* とても長い(199文字)

と思っています。なので、分かりやすさはそのままに、文字数を短くしたいと思っています。

それとは別に、ミートアップを類似したOSSプロダクトについて利用/開発している人たちで集まりやすくする工夫として、SNSで開催前に告知できるようにしたいと考えています。

その際に「取り組む予定のOSS」の回答を告知に掲載出来たら、「あ、このOSSに取り組む人がいるなら行ってみようかな」という開発者を呼び込めるかもしれないですし、ミートアップの参加者が今後増えていくきっかけになるかもしれません。

なので、回答時にSNSで告知することについて、同意が取れる内容を追加したいです。

まとめると、アンケート「取り組む予定のOSS」について、

* 文字数を今より短くする
* SNSに告知する同意がもらえるような内容を追加する

という変更をしたいです。

**Comment by knokmki612** [comment]
@koic @swamp09 12月以降のミートアップで変更できるように、相談させてください！

どなたでも意見がありましたらお聞かせください！

**Comment by knokmki612** [comment]
質問文の変更を考えるにあたって、共同で編集できるようにHackMDにそのためのページを用意してみました。

https://hackmd.io/BwVgDAjGDMULQmBAZnALAdjMOBDARgGy5wCcATKRubuQMb7KxA==

今のところHackMDのアカウントを持っていない方でも編集できるようにしてあります。

**Comment by knokmki612** [comment]
> SNSに告知する同意がもらえるような内容

こちらは、選択式の設問を別途追加したほうが良い気がしてきました

**Comment by tdtds** [comment]
個人名と併記するわけでないなら別に個人情報ではないので、SNSでの利用はとくに同意を求める必要はないのでは?

**Comment by knokmki612** [comment]
@tdtds 
そういうものなのですか。参考になります。
同意を求めないとして、アンケートの用途を明記する必要はあると思うのですが、そちらはいかかでしょうか？

**Comment by tdtds** [comment]
んー、単に「この項目はSNS等で共有されます」とか?

**Comment by knokmki612** [comment]
@tdtds 
ありがとうございます！
[質問文](https://hackmd.io/BwVgDAjGDMULQmBAZnALAdjMOBDARgGy5wCcATKRubuQMb7KxA==)に書き足す形で反映してみました。

**Comment by tdtds** [comment]
文体をすこし調整してみたよ。

**Comment by knokmki612** [comment]
変更してアンケートの内容が告知に使えるようになりました。ありがとうございました。
