### ISSUE TITLE
2018-06-09 進行役であった改善したいところについて

### ISSUE THREAD

**Issue by chigix** [oss-gate/retrospective#99]
（ふりかえり用に気づいたことを書く時は↓を参考にしてください。参考にしたら↓は消して構いません。ふりかえり用でないときはここに書いていることは気にせず全部消して書いてください。）

次の3つの観点で気づいたことを集めています。

  * よかったこと
  * 困ったこと
    * 進行役の案内ドキュメントがないので、事前に準備が足りるかどうか、初めて進行役を担当する人は気づけないです。
  * これから試したいこと
    * [https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md] のファイル名前を「scenario_note.md」 に変えた方が分かりやすいとは思います。
      * [scenario.md] と [scenario.rb]二つのファイルが全部あるので、markdown ファイルはスライドのためのノートとは思わなくなってしまいます。
    * スライドはほぼpdfの形で説明するので、専門のプレゼンソフトみたいにカンニングノートを自分のスクリーンに映るのはできません。それで、[スライドのカンニングノート](https://github.com/oss-gate/workshop/blob/9088ad04bf510ad7f0a5652af7900c9132900cad/tutorial/scenario.md)を事前にプリントして用意するのは facilitator-friendly だと思います。
    * `aggregate.rb` の使い方又は「ワークショップの振り返り」について、具体的なやり方と `aggregate.rb` の扱い説明はないので、今日終わった後、pull request で追加を出します。

**Comment by y-goto** [comment]
スライドの最新版は、PDFじゃなくてscenario.rbのファイルなんですよね。で、それをrabbitっていう須藤さんが作成したOSSをつかって表示する仕組みになっています。そのあたりの説明もあったほうがよいかもしれませんね。

**Comment by chigix** [comment]
直接 workshop のレポジトリ向けの Continuous Integration  環境を立てれば、`git push` 又は `pull request` を出すとき、直接 CI 環境がチェックしたり、ビルディングしたりしてくれるので、そして、 PDF の自動作成は別に改めて用意しなくても、直接 CI 環境の Building History からダウンロードできるかなぁと思っています。

**Comment by knokmki612** [comment]
https://oss-gate.github.io に「進行役をすることになったら」というページを追加して、

1. スライドの場所を確認しよう！
2. シナリオを読もう！
3. 任意: Youtubeで実際の進行をみてみよう！
...

みたいな、当日までに準備としてやっておくと良いことが分かるページはどうかなという話をしました

(私作りたいです！)

**Comment by knokmki612** [comment]
ページを書いてプルリクを出したので、興味ある方はチェックしてツッコミください！

**Comment by knokmki612** [comment]
https://github.com/oss-gate/retrospective/issues/99#issue-330857609 以降にあがっているもので私が思ったこと

> 進行役の案内ドキュメントがない

これは私がいまプルリクで出しているもので解決できそう

> scenario.md のファイル名前を scenario_note.md に変えた方が分かりやすい

これはたしかにscenario.rabとファイル名が同じなのは混同して良くない気がするので、scenario.mdの名前は変えたほうが良い気がします。 @kou どうでしょうか？

> scenario.mdをカンニングノートとして使う

進行役が当日の説明するときに必要なことはスライドに書いてあって、説明する際にカンニングノートを用意しなくても大丈夫なようになっていると個人的には思っています。

また、scenario.mdは開催前の事前の準備として確認したり、当日のハンズオン中に確認するような使い方で進行の理解に役立つものかなと思っています。

なので、説明している瞬間にscenario.mdが目に入る状態である必要性は低いかなと思っています。

> aggregate.rbの使い方

これは https://github.com/oss-gate/workshop/commit/675409456989de52bd15930f5eb4b1ac82a3c027#diff-5815e5be66bfadb55f2c6e94653bc0cf で反映されましたね！

> CIからPDFの最新版が落とせるようにする https://github.com/oss-gate/retrospective/issues/99#issuecomment-395947342

これはPDFにせよscenario.rabにせよ、rabbitのエコシステム( https://rabbit-shocker.org/ja/users.html )でスライドが提供されているんですよね。ローカルのscenario.rabが最新なのはそうですが、[須藤さんがやらなくてもrake publishでローカル以外も更新できそう](https://github.com/oss-gate/workshop/blob/master/tutorial/README.md#%E5%85%AC%E9%96%8B)なので試してみます

> rabbitの説明もあったほうがよいかも https://github.com/oss-gate/retrospective/issues/99#issuecomment-395946786

うーん、そうかもしれませんね

**Comment by knokmki612** [comment]
> [須藤さんがやらなくてもrake publishでローカル以外も更新できそう](https://github.com/oss-gate/workshop/blob/master/tutorial/README.md#%E5%85%AC%E9%96%8B)なので試してみます

rubygemsへのアップロード初めてだったんですけど、rubygemsのoss-gateのパスワードが分からなかったのでアップロードできませんでした(まあそりゃそうか)

**Comment by hiroyuki-sato** [comment]
@knokmki612 
https://rubygems.org/gems/rabbit-slide-oss-gate-introduction-japanese
これのownerを見るとわかりますが、こちらのスライドは須藤さんとoss-gateのアカウントがアップロードできます。同様に @knokmki612 さんを追加すればoss-gateのパスワードを知らなくてもアップロードできます。

**Comment by knokmki612** [comment]
@hiroyuki-sato ありがとうございます！

https://guides.rubygems.org/command-reference/#gem-owner

多分ownerな人が私を `gem owner -a` してくれるとアップロードできるんですね。しかしそうするとoss-gateというアカウントが別途ある意図が気になります
